### ISSUE TITLE
/opt/openshift-auth-proxy/run.sh: 23: num: not found

### ISSUE THREAD

**Issue by Sarcouy** [fabric8io/openshift-auth-proxy#14]
Hi! 
I am trying to use your fabric8/openshift-auth-proxy container and i encounter an issue.
(i ran it nicely - with all parameters set - in my openshift before, here i'll describe how to see the issue)

run the container :
`docker run -e OCP_AUTH_PROXY_MEMORY_LIMIT=64m  fabric8/openshift-auth-proxy`

> /opt/openshift-auth-proxy/run.sh: 23: /opt/openshift-auth-proxy/run.sh: num: not found

My setup is : 

` uname -a `
> Linux marmotte 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

`docker version`
> Client:
>  Version:      17.04.0-ce
>  API version:  1.28
>  Go version:   go1.7.5
>  Git commit:   4845c56
>  Built:        Mon Apr  3 18:07:42 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.04.0-ce
>  API version:  1.28 (minimum version 1.12)
>  Go version:   go1.7.5
>  Git commit:   4845c56
>  Built:        Mon Apr  3 18:07:42 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

`Docker info`

> Containers: 31
>  Running: 0
>  Paused: 0
>  Stopped: 31
> Images: 179
> Server Version: 17.04.0-ce
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 198
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: bridge host macvlan null overlay
> Swarm: active
>  NodeID: l4fj94ot6a3cjqvhtlzznb7fo
>  Is Manager: true
>  ClusterID: 9i766vdidv3t0p5ktth680qq8
>  Managers: 1
>  Nodes: 1
>  Orchestration:
>   Task History Retention Limit: 5
>  Raft:
>   Snapshot Interval: 10000
>   Number of Old Snapshots to Retain: 0
>   Heartbeat Tick: 1
>   Election Tick: 3
>  Dispatcher:
>   Heartbeat Period: 5 seconds
>  CA Configuration:
>   Expiry Duration: 3 months
>  Node Address: 192.168.1.46
>  Manager Addresses:
>   192.168.1.46:2377
> Runtimes: runc
> Default Runtime: runc
> Init Binary: 
> containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
> runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
> init version: 949e6fa
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.4.0-77-generic
> Operating System: Ubuntu 16.04.2 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 7.699GiB
> Name: marmotte
> ID: RCGT:ZMP7:RYZH:ZGIV:H5HD:KGMD:PAPL:CSWQ:NLTY:ABJG:RDJC:WBIC
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: No swap limit support
> 

I solved it on by changing first line in your run.sh file (not sure it's a good way of doing it)

> changed #!/bin/sh by #!/bin/bash

**Comment by jcantrill** [comment]
I would be surprised if that fixed your issue given from my testing bash was unavailable in the base image.  Everything I could find the base image includes 'dash'

**Comment by Sarcouy** [comment]
Hi, 
The base image is node:0.10.36
I tryed : docker run -it node:0.10.36 bash
root@95a66baeb573:/# whereis bash 
bash: /bin/bash /etc/bash.bashrc /usr/share/man/man1/bash.1.gz

Maybe i didn't understand what you told me. 
But if i did, "/bin/bash" seems to be available.
Take a look [here](https://github.com/Sarcouy/openshift-auth-proxy), i forked the projects to make some tests, changed with bash, and it works :)

**Comment by jcantrill** [comment]
hmm... that is interesting given while working to add the memory calculation bits I was thwarted in using the bash grep commands I wanted to use.  I will need to revisit.

**Comment by jcantrill** [comment]
@Sarcouy please validates #15 resolves the issue for you

**Comment by Sarcouy** [comment]
@jcantrill yes #15   works, thanks!
