### ISSUE TITLE
End-of-life for Node 4

### ISSUE THREAD

**Issue by Reamer** [fabric8io/openshift-auth-proxy#30]
Hi,
Our docker image (https://github.com/fabric8io/openshift-auth-proxy/blob/master/Dockerfile.centos7#L1) use node in version 4. This version (https://github.com/nodejs/Release) in not supported from node developers.
The docker image node:4.7.2 is now around **17 month old**.

Are there any plans to update to a new base image?

Best Regards
Reamer

**Comment by jcantrill** [comment]
@Reamer No immediate plans.  Feel free to submit a PR to upgrade to a newer version
